name: Tests

defaults:
  run:
    shell: bash

on: [push]  # Runs on all push events

# TODO: If we want to excluse on main (when a coverage workflow will take care of that)
# on:  # Runs on any push event to any branch except master (the coverage workflow takes care of that)
#   push:
#     branches-ignore:
#       - 'main'

jobs:
  tests:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10", "3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: '**/pyproject.toml'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package with test dependencies
        run: python -m pip install ".[test]"

      - name: Run Tests
        run: make tests
